spring.application.name=marketplace-backend

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/marketplace

# Puerto
server.port=8080

# JWT (lo usaremos después)
jwt.secret=marketplace_secret_key_2026_lo_cambie_para_que_no_sea_tan_facil_de_adivinar
jwt.expiration=86400000

# Desactivar Spring Security por defecto temporalmente
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# configuracion mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/marketplace

#logging.level.org.springframework.security=DEBUG#